### ISSUE TITLE
Custom configuration files documentation

### ISSUE THREAD

**Issue by PeterArbaugh** [briandeconinck/ncsu-a11y-helper#2]
Hi,

We've been testing out the plugin on our dev environment and noticed that the documentation link (https://design.oit.ncsu.edu/docs/a11y-helper) leads to a 404. We'd like to set up a custom configuration file, so even if the documentation isn't complete do you have any guidance for how to get started?

Thanks a lot for developing this and for presenting it at WPCampus.  We've been wondering how to do something similar at NYU and your solution hits most of our requirements and has great UX.

Best,

Peter

**Comment by bethdeconinck** [comment]
Hi Peter!

Sorry to keep you waiting on this! My life was taken over by Gutenberg prep for a few months.

That link should now be live and redirect to https://accessibility.oit.ncsu.edu/wordpress-accessibility-helper/, which has some instructions on config files. The doc is still a work-in-progress, but should be enough to help you get started.

Let me know if you have any questions!

Brian
